<?php
$CONFIG = array (
  'instanceid' => 'ocg2gdrw3bn4',
  'passwordsalt' => 'JmCA.4rZS8WGukMzLOddOtPxckmizu',
  'secret' => 'GvlMsTnKm3R6RGu4156CtTD1hthh50tQN6yq6xMj1ugJ12Au',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.200.122',
  ),
  'datadirectory' => 'E:\\wamp2.5\\www\\owncloud\\data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloudnew',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_sun',
  'dbpassword' => 'q57x3wlaem7pfd3c8hw68zx8ib9zl7',
  'installed' => true,
  'rootname'=>'SWIFT',//设置初始化时的名称
  'mimetype'=>array(
  "documents"=>"
      'application/msword',
      'application/vnd.ms-word.document.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.template',

      'application/pdf',

      'application/vnd.ms-powerpoint',
      'application/vnd.ms-powerpoint.template.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.presentationml.template',
      'application/vnd.ms-powerpoint.addin.macroEnabled.12',
      'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
      'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',

      'application/vnd.ms-excel',
      'application/vnd.ms-excel.addin.macroEnabled.12',
      'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
      'application/vnd.ms-excel.sheet.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel.template.macroEnabled.12',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.template',

      'text/plain',
      'text/x-shellscript',
      'text/x-c',
      'text/x-c++src',
      'text/css',
      'text/csv',
      'text/x-c',
      'text/x-c++src',
      'text/html',
      'text/calendar',
      'text/impress',
      'text/markdown',
      'text/x-python',
      'text/reveal',
      'text/x-shellscript',
      'text/vcard',
      'application/xml'
  ",
  'pictures'=>"
       'image/bmp',
       'image/gif',
       'image/jpeg',
       'image/tiff',
       'image/svg+xml',
       'image/png'
  ",
  'videos'=>"
       'video/3gpp',
       'video/x-msvideo',
       'video/dv',
       'video/x-flv',
       'video/mp2t',
       'video/mp4',
       'video/x-matroska',
       'video/quicktime',
       'video/mpeg',
       'video/ogg',
       'video/dvd',
       'video/webm',
       'application/x-shockwave-flash',
       'video/x-ms-asf'
  ",
  'audios'=>"
       'audio/wav',
       'audio/ogg',
       'audio/mpeg',
       'audio/flac'
  ",
  'others'=>"
        'application/x-7z-compressed',
        'application/msaccess',
        'application/illustrator',
        'application/vnd.android.package-archive',
        'application/x-blender',
        'application/x-bin',
        'application/x-cbr',
        'application/coreldraw',
        'application/x-cbr',
        'application/x-deb',
        'application/vnd.ms-fontobject',
        'application/epub+zip',
        'application/postscript',
        'application/x-ms-dos-executable',
        'application/x-gzip',
        'application/javascript',
        'application/json',
        'application/x-iwork-keynote-sffkey',
        'application/x-krita',
        'application/msaccess',
        'application/x-mobipocket-ebook',
        'application/x-msi',
        'application/x-iwork-numbers-sffnumbers',
        'application/vnd.oasis.opendocument.formula',
        'application/vnd.oasis.opendocument.graphics',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.spreadsheet',
        'application/vnd.oasis.opendocument.text',
        'font/opentype',
        'application/x-iwork-pages-sffpages',
        'application/x-php',
        'application/x-perl',
        'application/postscript',
        'application/x-photoshop',
        'application/x-rar-compressed',
        'application/sgf',
        'application/x-tar',
        'application/x-compressed',
        'application/x-tex',
        'application/x-font-ttf',
        'application/font-woff',
        'application/x-gimp',
        'application/zip'
  ",
  ),
  'swift' => 
  array (
    'user' => 'admin',
    'bucket' => '',
    'region' => 'RegionOne',
    'key' => 'admin',
    'tenant' => 'adminTenant',
    'password' => 'admin',
    'service_name' => 'swift',
    'url' => 'http://192.168.200.182:5000/v2.0',
    'timeout' => '',
  ),
);
